{% set name = "amset" %}
{% set version = "0.4.16" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amset-{{ version }}.tar.gz
  sha256: b122e729c21074225661c0fa66674c7699c55db12d5d80aa379a5de4f63d374d

build:
  number: 0
  noarch: python
  entry_points:
    - amset = amset.tools.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - boltztrap2 ==20.7.1
    - click ==7.1.2
    - h5py ==3.2.1
    - interpolation ==2.2.1
    - matplotlib-base ==3.4.1
    - memory_profiler ==0.58.0
    - monty ==2021.3.3
    - numpy ==1.20.2
    - numba ==0.53.1
    - pyfftw ==0.12.0
    - pymatgen ==2022.0.6
    - python >=3.5
    - quadpy ==0.16.6
    - scipy ==1.6.2
    - spglib ==1.16.1
    - sumo ==2.2.3
    - tabulate ==0.8.9
    - tqdm ==4.60.0

test:
  imports:
    - amset
    - amset.core
  commands:
    - pip check
    - amset --help
  requires:
    - pip

about:
  home: https://hackingmaterials.lbl.gov/amset/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Electronic transport properties from first-principles calculations
  description: |
    AMSET is a package for calculating electronic transport properties 
    from first-principles calculations.
  doc_url: https://hackingmaterials.lbl.gov/amset/
  dev_url: https://github.com/hackingmaterials/amset

extra:
  recipe-maintainers:
    - jan-janssen
