{% set name = "amset" %}
{% set version = "0.4.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amset-{{ version }}.tar.gz
  sha256: 04dc0d5f59e78dbfa958dd0c3667902969938e4b3c035b1b06d1d4d24b80c6d2

build:
  number: 0
  noarch: python
  entry_points:
    - amset = amset.tools.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - boltztrap2 ==20.7.1
    - click ==7.1.2
    - h5py ==3.1.0
    - interpolation ==2.1.6
    - matplotlib-base ==3.3.4
    - memory_profiler ==0.58.0
    - monty ==4.0.2
    - numpy ==1.19.5
    - numba ==0.51.2
    - pyfftw ==0.12.0
    - pymatgen ==2020.12.31
    - python >=3.5
    - quadpy ==0.16.5
    - scipy ==1.6.0
    - spglib ==1.16.1
    - sumo ==2.2.1
    - tabulate ==0.8.7
    - tqdm ==4.56.0

test:
  imports:
    - amset
    - amset.core
  commands:
    - pip check
    - amset --help
  requires:
    - pip

about:
  home: https://hackingmaterials.lbl.gov/amset/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Electronic transport properties from first-principles calculations
  description: |
    AMSET is a package for calculating electronic transport properties 
    from first-principles calculations.
  doc_url: https://hackingmaterials.lbl.gov/amset/
  dev_url: https://github.com/hackingmaterials/amset

extra:
  recipe-maintainers:
    - jan-janssen
