{% set name = "amset" %}
{% set version = "0.4.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amset-{{ version }}.tar.gz
  sha256: 7e2a626697d43cbb4881f2488436d7b9921c1749ed73319c59bfacc700fefc38

build:
  number: 0
  noarch: python
  entry_points:
    - amset = amset.tools.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - boltztrap2  # ==20.7.1
    - click  # ==8.0.1
    - h5py  # ==3.4.0
    - interpolation  # ==2.2.1
    - matplotlib-base  # ==3.4.3
    - memory_profiler  # ==0.58.0
    - monty  # ==2021.8.17
    - numpy  # ==1.21.2
    - numba  # ==0.53.1
    - pyfftw  # ==0.12.0
    - pymatgen  # ==2022.0.13
    - python >=3.5
    - quadpy  # ==0.16.9
    - scipy  # ==1.7.1
    - spglib  # ==1.16.2
    - sumo  # ==2.2.5
    - tabulate  # ==0.8.9
    - tqdm  # ==4.62.2

test:
  imports:
    - amset
    - amset.core
  commands:
    - pip check
    - amset --help
  requires:
    - pip

about:
  home: https://hackingmaterials.lbl.gov/amset/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Electronic transport properties from first-principles calculations
  description: |
    AMSET is a package for calculating electronic transport properties 
    from first-principles calculations.
  doc_url: https://hackingmaterials.lbl.gov/amset/
  dev_url: https://github.com/hackingmaterials/amset

extra:
  recipe-maintainers:
    - jan-janssen
