{% set name = "amset" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/amset-{{ version }}.tar.gz
  sha256: 77d839167d061eaf869f1f98ba499d53a3036b532d96d5ef0ed88cccf8509184

build:
  entry_points:
    - amset = amset.tools.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - numpy
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - boltztrap2
    - click
    - h5py
    - interpolation
    - matplotlib-base
    - memory_profiler
    - monty
    - numba
    - pyfftw
    - pymatgen >=2022.0.16
    - python >={{ python_min }}
    - scipy
    - spglib
    - sumo
    - tabulate
    - tqdm

test:
  imports:
    - amset
  commands:
    - pip check
    - amset --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hackingmaterials/amset
  summary: AMSET is a tool to calculate carrier transport properties from ab initio calculation data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
