{% set name = "amset" %}
{% set version = "0.4.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/amset-{{ version }}.tar.gz
  sha256: 0c4b0e4a0650a18754365c3e455ac26d709f3cbbb67fbcd2408453e533a872d8

build:
  entry_points:
    - amset = amset.tools.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - numpy
    - pip
    - python >=3.8
  run:
    - boltztrap2
    - click
    - h5py
    - interpolation
    - matplotlib-base
    - memory_profiler
    - monty
    - numba
    - pyfftw
    - pymatgen >=2022.0.16
    - python >=3.8
    - scipy
    - spglib
    - sumo
    - tabulate
    - tqdm

test:
  imports:
    - amset
  commands:
    - pip check
    - amset --help
  requires:
    - pip

about:
  home: https://github.com/hackingmaterials/amset
  summary: AMSET is a tool to calculate carrier transport properties from ab initio calculation data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
